language: node_js

node_js:
  - "node"
  - "12"
  - "10"

matrix:
  include:
    - os: linux
      dist: bionic
      env:
        - IMG=existdb/existdb:5.2.0
        - API_XAR=https://github.com/evolvedbinary/fusion-studio-api/releases/download/0.1.1/fusion-studio-api-0.1.1.xar
      services:
        - docker
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libx11-dev
            - libxkbfile-dev
            - libgconf2-4
      before_install:
        - docker pull $IMG
        - docker create  --name exist-ci -p 8080:8080 $IMG
        - wget $API_XAR
        - docker cp ./*.xar exist-ci:exist/autodeploy
        - docker start exist-ci
        - rm *.xar
        - sleep 10
      script:
        - yarn run cypress run --record
    - os: osx
      osx_image: xcode12
      addons:
        homebrew:
          packages:
            - yarn
    #  - os: windows

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - YARN_GPG=no

install:
  - yarn
  - yarn run sass
  - yarn run rebuild:browser
  - cd browser-app
  - yarn start &
  - cd ..

before_script:
  - yarn test

before_cache:
  - rm -rf $ELECTRON_BUILDER_CACHE/wine

cache:
  directories:
    - $HOME/.cache/yarn
    - $HOME/.npm
    - node_modules
    - $ELECTRON_CACHE
    - $ELECTRON_BUILDER_CACHE
