dist: xenial
osx_image: xcode10.1

language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - YARN_GPG=no

os:
  - linux
  - osx
  - windows

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
  - export PATH=$HOME/.yarn/bin:$PATH
  - node --version && yarn --version && python --version

install:
  - yarn

script:
  - yarn run sass

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libx11-dev
      - libxkbfile-dev
