version: '{branch}-{build}'

environment:
  nodejs_version: 8.16.0
  YARN_GPG: no

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804

cache:
  - node_modules                        # local npm modules
  - '%APPDATA%\npm-cache'               # npm cache

# used on Ubuntu
stack: node 8

install:
  - node --version && yarn --version && python --version
  - cmd: yarn
  - sh: yarn

build_script:
  - yarn run rebuild:browser && yarn run rebuild:electron
